baseURL = 'https://andrespas.com/'
languageCode = 'en-us'
title = 'Andres Pastrana'
theme = 'ananke'

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 2

[params]
description = "Software engineer focused on performance and optimization systems."
custom_css = ["custom.css"]

# Configure which networks to show (REQUIRED)
[params.ananke.social.follow]
networks = ["github", "linkedin"]

# Configure each individual network (REQUIRED)
[params.ananke.social.github]
username = "rapastranac"

[params.ananke.social.linkedin]
username = "andrepas"